# Generated by Django 2.2.5 on 2019-11-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogproduct',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
